/**
 * LIO - Order Management API
 * API de gerenciamento de pedidos da LIO.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


/**
 * Informações sobre o cartão utilizado na transação.
 **/
@ApiModel(description = "Informações sobre o cartão utilizado na transação.")
public class Card  {
  
  public enum BrandEnum {
     VISA,  MASTER, 
  };
  @SerializedName("brand")
  private BrandEnum brand = null;
  @SerializedName("bin")
  private Integer bin = null;
  @SerializedName("last")
  private Integer last = null;

  /**
   * Bandeira do cartão.
   **/
  @ApiModelProperty(required = true, value = "Bandeira do cartão.")
  public BrandEnum getBrand() {
    return brand;
  }
  public void setBrand(BrandEnum brand) {
    this.brand = brand;
  }

  /**
   * Bin (primeiros 6 dígitos) do cartão.
   **/
  @ApiModelProperty(required = true, value = "Bin (primeiros 6 dígitos) do cartão.")
  public Integer getBin() {
    return bin;
  }
  public void setBin(Integer bin) {
    this.bin = bin;
  }

  /**
   * Last (últimos 4 dígitos) do cartão.
   **/
  @ApiModelProperty(required = true, value = "Last (últimos 4 dígitos) do cartão.")
  public Integer getLast() {
    return last;
  }
  public void setLast(Integer last) {
    this.last = last;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Card card = (Card) o;
    return (brand == null ? card.brand == null : brand.equals(card.brand)) &&
        (bin == null ? card.bin == null : bin.equals(card.bin)) &&
        (last == null ? card.last == null : last.equals(card.last));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (brand == null ? 0: brand.hashCode());
    result = 31 * result + (bin == null ? 0: bin.hashCode());
    result = 31 * result + (last == null ? 0: last.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Card {\n");
    
    sb.append("  brand: ").append(brand).append("\n");
    sb.append("  bin: ").append(bin).append("\n");
    sb.append("  last: ").append(last).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
