/**
 * LIO - Order Management API
 * API de gerenciamento de pedidos da LIO.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import java.util.Date;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class OrderItem  {
  
  @SerializedName("sku")
  private String sku = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("unit_price")
  private Integer unitPrice = null;
  @SerializedName("quantity")
  private Integer quantity = null;
  public enum UnitOfMeasureEnum {
     EACH,  HOURS,  DAYS,  SECONDS,  CRATE_OF_12,  SIX_PACK,  GALLON,  LITRE, 
  };
  @SerializedName("unit_of_measure")
  private UnitOfMeasureEnum unitOfMeasure = null;
  @SerializedName("details")
  private String details = null;
  @SerializedName("created_at")
  private Date createdAt = null;
  @SerializedName("updated_at")
  private Date updatedAt = null;

  /**
   * SKU do produto.
   **/
  @ApiModelProperty(value = "SKU do produto.")
  public String getSku() {
    return sku;
  }
  public void setSku(String sku) {
    this.sku = sku;
  }

  /**
   * Nome do produto.
   **/
  @ApiModelProperty(value = "Nome do produto.")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Descrição do produto.
   **/
  @ApiModelProperty(value = "Descrição do produto.")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * Valor unitário do produto. Exemplo: O valor de R$ 10,00 é representado como 1000.
   **/
  @ApiModelProperty(required = true, value = "Valor unitário do produto. Exemplo: O valor de R$ 10,00 é representado como 1000.")
  public Integer getUnitPrice() {
    return unitPrice;
  }
  public void setUnitPrice(Integer unitPrice) {
    this.unitPrice = unitPrice;
  }

  /**
   * Quantidade de itens. Caso não seja informado será considerado o valor 1.
   **/
  @ApiModelProperty(value = "Quantidade de itens. Caso não seja informado será considerado o valor 1.")
  public Integer getQuantity() {
    return quantity;
  }
  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  /**
   * Unidade de medida.
   **/
  @ApiModelProperty(required = true, value = "Unidade de medida.")
  public UnitOfMeasureEnum getUnitOfMeasure() {
    return unitOfMeasure;
  }
  public void setUnitOfMeasure(UnitOfMeasureEnum unitOfMeasure) {
    this.unitOfMeasure = unitOfMeasure;
  }

  /**
   * Detalhes do produto.
   **/
  @ApiModelProperty(value = "Detalhes do produto.")
  public String getDetails() {
    return details;
  }
  public void setDetails(String details) {
    this.details = details;
  }

  /**
   * Data da criação/inclusão do item no pedido. A data deve estar no formato: YYYY-MM-DDThh:mm:ssZ (Exemplo: 20151020T13:13:29.000Z)
   **/
  @ApiModelProperty(required = true, value = "Data da criação/inclusão do item no pedido. A data deve estar no formato: YYYY-MM-DDThh:mm:ssZ (Exemplo: 20151020T13:13:29.000Z)")
  public Date getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }

  /**
   * Data da última atualização do item no pedido. A data deve estar no formato: YYYY-MM-DDThh:mm:ssZ (Exemplo: 20151020T13:13:29.000Z)
   **/
  @ApiModelProperty(required = true, value = "Data da última atualização do item no pedido. A data deve estar no formato: YYYY-MM-DDThh:mm:ssZ (Exemplo: 20151020T13:13:29.000Z)")
  public Date getUpdatedAt() {
    return updatedAt;
  }
  public void setUpdatedAt(Date updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderItem orderItem = (OrderItem) o;
    return (sku == null ? orderItem.sku == null : sku.equals(orderItem.sku)) &&
        (name == null ? orderItem.name == null : name.equals(orderItem.name)) &&
        (description == null ? orderItem.description == null : description.equals(orderItem.description)) &&
        (unitPrice == null ? orderItem.unitPrice == null : unitPrice.equals(orderItem.unitPrice)) &&
        (quantity == null ? orderItem.quantity == null : quantity.equals(orderItem.quantity)) &&
        (unitOfMeasure == null ? orderItem.unitOfMeasure == null : unitOfMeasure.equals(orderItem.unitOfMeasure)) &&
        (details == null ? orderItem.details == null : details.equals(orderItem.details)) &&
        (createdAt == null ? orderItem.createdAt == null : createdAt.equals(orderItem.createdAt)) &&
        (updatedAt == null ? orderItem.updatedAt == null : updatedAt.equals(orderItem.updatedAt));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (sku == null ? 0: sku.hashCode());
    result = 31 * result + (name == null ? 0: name.hashCode());
    result = 31 * result + (description == null ? 0: description.hashCode());
    result = 31 * result + (unitPrice == null ? 0: unitPrice.hashCode());
    result = 31 * result + (quantity == null ? 0: quantity.hashCode());
    result = 31 * result + (unitOfMeasure == null ? 0: unitOfMeasure.hashCode());
    result = 31 * result + (details == null ? 0: details.hashCode());
    result = 31 * result + (createdAt == null ? 0: createdAt.hashCode());
    result = 31 * result + (updatedAt == null ? 0: updatedAt.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderItem {\n");
    
    sb.append("  sku: ").append(sku).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  unitPrice: ").append(unitPrice).append("\n");
    sb.append("  quantity: ").append(quantity).append("\n");
    sb.append("  unitOfMeasure: ").append(unitOfMeasure).append("\n");
    sb.append("  details: ").append(details).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  updatedAt: ").append(updatedAt).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
