/**
 * LIO - Order Management API
 * API de gerenciamento de pedidos da LIO.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.OrdersPaymentProductSub;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Informações sobre o produto de pagamento utilizado.
 **/
@ApiModel(description = "Informações sobre o produto de pagamento utilizado.")
public class OrdersPaymentProduct {
  
  @SerializedName("number")
  private Integer number = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("sub")
  private OrdersPaymentProductSub sub = null;

  /**
   * Identificação numérica do produto primário da Cielo.
   **/
  @ApiModelProperty(required = true, value = "Identificação numérica do produto primário da Cielo.")
  public Integer getNumber() {
    return number;
  }
  public void setNumber(Integer number) {
    this.number = number;
  }

  /**
   * Nome do produto primário utilizado.
   **/
  @ApiModelProperty(required = true, value = "Nome do produto primário utilizado.")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public OrdersPaymentProductSub getSub() {
    return sub;
  }
  public void setSub(OrdersPaymentProductSub sub) {
    this.sub = sub;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrdersPaymentProduct ordersPaymentProduct = (OrdersPaymentProduct) o;
    return (this.number == null ? ordersPaymentProduct.number == null : this.number.equals(ordersPaymentProduct.number)) &&
        (this.name == null ? ordersPaymentProduct.name == null : this.name.equals(ordersPaymentProduct.name)) &&
        (this.sub == null ? ordersPaymentProduct.sub == null : this.sub.equals(ordersPaymentProduct.sub));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.number == null ? 0: this.number.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.sub == null ? 0: this.sub.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrdersPaymentProduct {\n");
    
    sb.append("  number: ").append(number).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  sub: ").append(sub).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
