/**
 * LIO - Order Management API
 * API de gerenciamento de pedidos da LIO.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Informações sobre o cartão utilizado na transação.
 **/
@ApiModel(description = "Informações sobre o cartão utilizado na transação.")
public class OrdersCard {
  
  public enum BrandEnum {
     VISA,  MASTERCARD,  ELO,  DINERS,  AMEX,  AURA, 
  };
  @SerializedName("brand")
  private BrandEnum brand = null;
  @SerializedName("bin")
  private Integer bin = null;
  @SerializedName("last")
  private Integer last = null;

  /**
   * Bandeira do cartão.
   **/
  @ApiModelProperty(required = true, value = "Bandeira do cartão.")
  public BrandEnum getBrand() {
    return brand;
  }
  public void setBrand(BrandEnum brand) {
    this.brand = brand;
  }

  /**
   * Bin (primeiros 6 dígitos) do cartão.
   **/
  @ApiModelProperty(required = true, value = "Bin (primeiros 6 dígitos) do cartão.")
  public Integer getBin() {
    return bin;
  }
  public void setBin(Integer bin) {
    this.bin = bin;
  }

  /**
   * Last (últimos 4 dígitos) do cartão.
   **/
  @ApiModelProperty(required = true, value = "Last (últimos 4 dígitos) do cartão.")
  public Integer getLast() {
    return last;
  }
  public void setLast(Integer last) {
    this.last = last;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrdersCard ordersCard = (OrdersCard) o;
    return (this.brand == null ? ordersCard.brand == null : this.brand.equals(ordersCard.brand)) &&
        (this.bin == null ? ordersCard.bin == null : this.bin.equals(ordersCard.bin)) &&
        (this.last == null ? ordersCard.last == null : this.last.equals(ordersCard.last));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.brand == null ? 0: this.brand.hashCode());
    result = 31 * result + (this.bin == null ? 0: this.bin.hashCode());
    result = 31 * result + (this.last == null ? 0: this.last.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrdersCard {\n");
    
    sb.append("  brand: ").append(brand).append("\n");
    sb.append("  bin: ").append(bin).append("\n");
    sb.append("  last: ").append(last).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
